const users = [
    { id: 1 , nombre: "Alice" },
    { id: 2 , nombre: "Bob" },
    { id: 3 , nombre: "Charlie" },
    { id: 4 , nombre: "Dave" },
    { id: 5 , nombre: "Eve" },
];

const games = [
  { id: 0, nombre: "The Legend of Zelda: Ocarina of Time" },
  { id: 1, nombre: "Tony Hawk's Pro Skater 2" },
  { id: 2, nombre: "Grand Theft Auto IV" },
  { id: 3, nombre: "SoulCalibur" },
  { id: 4, nombre: "Grand Theft Auto IV" },
  { id: 5, nombre: "Super Mario Galaxy" },
  { id: 6, nombre: "Super Mario Galaxy 2" },
  { id: 7, nombre: "Red Dead Redemption 2" },
  { id: 8, nombre: "Grand Theft Auto V" },
  { id: 9, nombre: "Grand Theft Auto V" },
  { id: 10, nombre: "Grand Theft Auto V" },
  { id: 11, nombre: "Tony Hawk's Pro Skater 2" },
  { id: 12, nombre: "The Legend of Zelda: Breath of the Wild" },
  { id: 13, nombre: "Tony Hawk's Pro Skater 3" },
  { id: 14, nombre: "Perfect Dark" },
  { id: 15, nombre: "Red Dead Redemption 2" },
  { id: 16, nombre: "Grand Theft Auto V" },
  { id: 17, nombre: "Metroid Prime" },
  { id: 18, nombre: "Grand Theft Auto III" },
  { id: 19, nombre: "Super Mario Odyssey" },
  { id: 20, nombre: "Halo: Combat Evolved" },
  { id: 21, nombre: "NFL 2K1" },
  { id: 22, nombre: "Half-Life 2" },
  { id: 23, nombre: "Grand Theft Auto V" },
  { id: 24, nombre: "The Legend of Zelda: Breath of the Wild" },
  { id: 25, nombre: "BioShock" },
  { id: 26, nombre: "GoldenEye 007" },
  { id: 27, nombre: "Uncharted 2: Among Thieves" },
  { id: 28, nombre: "Resident Evil 4" },
  { id: 29, nombre: "The Orange Box" },
  { id: 30, nombre: "The Orange Box" },
  { id: 31, nombre: "Batman: Arkham City" },
  { id: 32, nombre: "Tekken 3" },
  { id: 33, nombre: "Mass Effect 2" },
  { id: 34, nombre: "The Legend of Zelda: Twilight Princess" },
  { id: 35, nombre: "The Elder Scrolls V: Skyrim" },
  { id: 36, nombre: "Half-Life" },
  { id: 37, nombre: "Resident Evil 4" },
  { id: 38, nombre: "The Legend of Zelda: The Wind Waker" },
  { id: 39, nombre: "Gran Turismo" },
  { id: 40, nombre: "BioShock" },
  { id: 41, nombre: "Metal Gear Solid 2: Sons of Liberty" },
  { id: 42, nombre: "Grand Theft Auto Double Pack" },
  { id: 43, nombre: "Baldur's Gate II: Shadows of Amn" },
  { id: 44, nombre: "Grand Theft Auto: San Andreas" },
  { id: 45, nombre: "Grand Theft Auto: Vice City" },
  { id: 46, nombre: "LittleBigPlanet" },
  { id: 47, nombre: "The Legend of Zelda Collector's Edition" },
  { id: 48, nombre: "Red Dead Redemption" },
  { id: 49, nombre: "Gran Turismo 3: A-Spec" },
  { id: 50, nombre: "Halo 2" },
  { id: 51, nombre: "The Legend of Zelda: A Link to the Past" },
  { id: 52, nombre: "The Legend of Zelda: Majora's Mask" },
  { id: 53, nombre: "The Last of Us" },
  { id: 54, nombre: "The Legend of Zelda: Twilight Princess" },
  { id: 55, nombre: "Madden NFL 2003" },
  { id: 56, nombre: "Tony Hawk's Pro Skater 2" },
  { id: 57, nombre: "Persona 5 Royal" },
  { id: 58, nombre: "The Last of Us Remastered" },
  { id: 59, nombre: "Portal 2" },
  { id: 60, nombre: "Red Dead Redemption" },
  { id: 61, nombre: "Portal 2" },
  { id: 62, nombre: "Metal Gear Solid V: The Phantom Pain" },
  { id: 63, nombre: "Portal 2" },
  { id: 64, nombre: "World of Goo" },
  { id: 65, nombre: "The Elder Scrolls V: Skyrim" },
  { id: 66, nombre: "BioShock Infinite" },
  { id: 67, nombre: "Final Fantasy IX" },
  { id: 68, nombre: "Call of Duty: Modern Warfare 2" },
  { id: 69, nombre: "God of War" },
  { id: 70, nombre: "Tony Hawk's Pro Skater 4" },
  { id: 71, nombre: "Devil May Cry" },
  { id: 72, nombre: "Call of Duty 4: Modern Warfare" },
  { id: 73, nombre: "Madden NFL 2002" },
  { id: 74, nombre: "Batman: Arkham City" },
  { id: 75, nombre: "Mass Effect 2" },
  { id: 76, nombre: "The Legend of Zelda: Ocarina of Time 3D" },
  { id: 77, nombre: "Chrono Cross" },
  { id: 78, nombre: "Celeste" },
  { id: 79, nombre: "BioShock" },
  { id: 80, nombre: "Mass Effect 2" },
  { id: 81, nombre: "Grand Theft Auto: Vice City" },
  { id: 82, nombre: "Madden NFL 2004" },
  { id: 83, nombre: "Gears of War" },
  { id: 84, nombre: "The Elder Scrolls IV: Oblivion" },
  { id: 85, nombre: "Sid Meier's Civilization II" },
  { id: 86, nombre: "Quake" },
  { id: 87, nombre: "Call of Duty 4: Modern Warfare" },
  { id: 88, nombre: "BioShock Infinite" },
  { id: 89, nombre: "Halo 3" },
  { id: 90, nombre: "Ninja Gaiden Black" },
  { id: 91, nombre: "The Elder Scrolls IV: Oblivion" },
  { id: 92, nombre: "Street Fighter IV" },
  { id: 93, nombre: "Super Mario Advance 4: Super Mario Bros. 3" },
  { id: 94, nombre: "Jet Grind Radio" },
  { id: 95, nombre: "Metal Gear Solid" },
  { id: 96, nombre: "Grim Fandango" },
  { id: 97, nombre: "Tom Clancy's Splinter Cell Chaos Theory" },
  { id: 98, nombre: "Burnout 3: Takedown" },
  { id: 99, nombre: "Diablo" },
];

module.exports = { users , games }
